services:
  parakeet-tdt-0.6b-v2-stt:
    build:
      context: .
      dockerfile: Dockerfile
    image: parakeet-tdt-0.6b-v2-stt:latest
    container_name: parakeet-tdt-0.6b-v2-stt

    entrypoint: ["python3", "app.py"]

    ports:
      - "5023:5023"
    expose:
      - "5023"

    volumes:
      - /home/ubuntu/characterxyz/development/parakeet-tdt-0.6b-v2/model:/app/model

    environment:
      PYTHONUNBUFFERED: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: unless-stopped
